services:
  postgres:
    image : pgvector/pgvector:pg16
    container_name : postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "ollama_data:/root/.ollama"
volumes:
  pgdata:
  ollama_data:
